version: "3.8"
volumes:
  php-fpm-socket:
  db-store:
services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    image: dtuj_circleci_app
    container_name: app
    volumes:
      - php-fpm-socket:/var/run/php-fpm
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3308
      - DB_DATABASE=${DB_NAME:-laravel_local}
      - DB_USERNAME=${DB_USER:-phper}
      - DB_PASSWORD=${DB_PASS:-secret}
      - APP_ENV=testing
      - LOG_REQUESTS=true

  web:
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    image: dtuj_circleci_web
    ports:
      - ${WEB_PORT:-82}:82
    volumes:
      - php-fpm-socket:/var/run/php-fpm
    environment:
      - WEB_PORT=82
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
        compress: "true"

  db:
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    image: dtuj_circleci_db
    ports:
      - ${DB_PORT:-3308}:3308
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-laravel_local}
      - MYSQL_USER=${DB_USER:-phper}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}
      - MYSQL_TCP_PORT=3308
